---
- name: Install apache on all servers
  hosts: all
  become: true
  tasks:
    - name: Install httpd
      dnf:
        name: httpd
        state: present
      when: ansible_facts['os_family'] == "RedHat"i

    - name: Start httpd
      service:
        name: httpd
        state: started
      when: ansible_facts['os_family'] == "RedHat"
      ignore_errors: yes

    - name: Intall apache2
      apt:
        name: apache2
        state: present
      when: ansible_facts['os_family'] == "Debian"

    - name: Start apache2
      service:
        name: apache2
        state: started
      when: ansible_facts['os_family'] == "Debian"

    - name: copying index file to path
      copy:
        src: /home/anadi/index.html
        dest: /var/www/html
        mode: 0666

