---
- name : uninstall apache from all servers
  hosts: all
  become: true
  tasks:
    - name: Stop httpd service
      service:
        name: httpd
        state: stopped
      when: ansible_facts['os_family'] == 'RedHat'
    - name: Uninstall httpd package
      dnf:
        name: httpd
        state: absent
      when: ansible_facts['os_family'] == 'RedHat'
    - name: stop apache2
      service:
        name: apache2
        state: stopped
      when: ansible_facts['os_family'] == "Debian"
    - name: uninstall apache2
      apt:
        name: apache2
        state: absent
      when: ansible_facts['os_family'] == "Debian"
