---
- name: uninstalling httpd
  hosts: all
  become: true
  tasks: 
  - name: Stop httpd
    service:
      name: httpd
      state: stopped
  - name: Remove httpd
    dnf:
      name: httpd
      state: removed
